import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
    {
        _id: uuid(),
        img: `${require("../../assets/images/shoe1.jfif")}`,
        title: "Nike",
        details: "Nike Air Force 1 '07 LV8'",
        rating: 4,
        price: 8295,
        gender: "men",
    },
    {
        _id: uuid(),
        img: `${require("../../assets/images/shoe2.jfif")}`,
        title: "Nike",
        details: "Nike Dunk High Retro SE",
        rating: 3,
        price: 10295,
        gender: "men",
    },
    {
        _id: uuid(),
        img: `${require("../../assets/images/shoe3.jfif")}`,
        title: "Nike",
        details: "Nike Air Force 1 '07 LV8'",
        rating: 2,
        price: 9695,
        gender: "women",
    },
    {
        _id: uuid(),
        img: `${require("../../assets/images/shoe1.jfif")}`,
        title: "Nike",
        details: "Nike Air Force 1 '07 LV8'",
        rating: 5,
        price: 8295,
        gender: "women",
    },
    {
        _id: uuid(),
        img: `${require("../../assets/images/shoe2.jfif")}`,
        title: "Nike",
        details: "Nike Dunk High Retro SE",
        rating: 5,
        price: 10295,
        gender: "men",
    },
    {
        _id: uuid(),
        img: `${require("../../assets/images/shoe3.jfif")}`,
        title: "Nike",
        details: "Nike Air Force 1 '07 LV8'",
        rating: 3,
        price: 9695,
        gender: "men",
    },
    {
        _id: uuid(),
        img: `${require("../../assets/images/shoe1.jfif")}`,
        title: "Nike",
        details: "Nike Air Force 1 '07 LV8'",
        rating: 1,
        price: 8295,
        gender: "women",
    },
    {
        _id: uuid(),
        img: `${require("../../assets/images/shoe2.jfif")}`,
        title: "Vans",
        details: "Nike Dunk High Retro SE",
        rating: 2,
        price: 10295,
        gender: "kids",
    },
    {
        _id: uuid(),
        img: `${require("../../assets/images/shoe3.jfif")}`,
        title: "Vans",
        details: "Nike Air Force 1 '07 LV8'",
        rating: 3,
        price: 9695,
        gender: "kids",
    },
    {
        _id: uuid(),
        img: `${require("../../assets/images/shoe2.jfif")}`,
        title: "Puma",
        details: "Nike Dunk High Retro SE",
        rating: 4,
        price: 10295,
        gender: "men",
    },
    {
        _id: uuid(),
        img: `${require("../../assets/images/shoe3.jfif")}`,
        title: "Puma",
        details: "Nike Air Force 1 '07 LV8'",
        rating: 4,
        price: 9695,
        gender: "men",
    },
    {
        _id: uuid(),
        img: `${require("../../assets/images/shoe1.jfif")}`,
        title: "Adidas",
        details: "Nike Air Force 1 '07 LV8'",
        rating: 5,
        price: 8295,
        gender: "women",
    },
    {
        _id: uuid(),
        img: `${require("../../assets/images/shoe2.jfif")}`,
        title: "Adidas",
        details: "Nike Dunk High Retro SE",
        rating: 2,
        price: 10295,
        gender: "kids",
    },
    {
        _id: uuid(),
        img: `${require("../../assets/images/shoe3.jfif")}`,
        title: "Adidas",
        details: "Nike Air Force 1 '07 LV8'",
        rating: 3,
        price: 9695,
        gender: "kids",
    },
];
