export const categories = [
    {
        id: 1,
        img: `${require("./assets/images/men.webp")}`,
        title: "MEN",
    },
    {
        id: 2,
        img: `${require("./assets/images/women.webp")}`,
        title: "WOMEN",
    },
    {
        id: 3,
        img: `${require("./assets/images/kids.webp")}`,
        title: "KIDS",
    },
];

export const products = [
    {
        id: 1,
        img: `${require("./assets/images/shoe1.jfif")}`,
        title: "Nike",
        details: "Nike Air Force 1 '07 LV8'",
        rating: 4,
        price: 8295,
    },
    {
        id: 2,
        img: `${require("./assets/images/shoe2.jfif")}`,
        title: "Nike",
        details: "Nike Dunk High Retro SE",
        rating: 4,
        price: 10295,
    },
    {
        id: 3,
        img: `${require("./assets/images/shoe3.jfif")}`,
        title: "Nike",
        details: "Nike Air Force 1 '07 LV8'",
        rating: 4,
        price: 9695,
    },
    {
        id: 4,
        img: `${require("./assets/images/shoe1.jfif")}`,
        title: "Nike",
        details: "Nike Air Force 1 '07 LV8'",
        rating: 4,
        price: 8295,
    },
    {
        id: 5,
        img: `${require("./assets/images/shoe2.jfif")}`,
        title: "Nike",
        details: "Nike Dunk High Retro SE",
        rating: 4,
        price: 10295,
    },
    {
        id: 6,
        img: `${require("./assets/images/shoe3.jfif")}`,
        title: "Nike",
        details: "Nike Air Force 1 '07 LV8'",
        rating: 4,
        price: 9695,
    },
    {
        id: 7,
        img: `${require("./assets/images/shoe1.jfif")}`,
        title: "Nike",
        details: "Nike Air Force 1 '07 LV8'",
        rating: 4,
        price: 8295,
    },
    {
        id: 8,
        img: `${require("./assets/images/shoe2.jfif")}`,
        title: "Nike",
        details: "Nike Dunk High Retro SE",
        rating: 4,
        price: 10295,
    },
    {
        id: 9,
        img: `${require("./assets/images/shoe3.jfif")}`,
        title: "Nike",
        details: "Nike Air Force 1 '07 LV8'",
        rating: 4,
        price: 9695,
    },
];
